[package]
edition = "2021"
name = "mp_rater"
version = "0.1.0"
[dependencies]
clap = "3.0.7"
env_logger = "0.9"
id3 = "0.6"
once_cell = "*"
log = "0.4"
mpd = "*"
notify-rust = "*"
serde_json = "1.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
